### PR TITLE
Merge Staging

### PR DESCRIPTION
**Pull request by xlcrr**

### CODE REVIEW

**Comment by xlcrr** [comment]
@sudoDeznit I messed up here recently, accidentally merged master into staging, I was trying to close the other PR and get the commits counted towards pushing to the master branch... does this look okay to you to merge into main?

**Comment by sudoDeznit** [comment]
@xlcrr I don't think it will be a good idea... There are commits like [4aa804d](https://github.com/OpenLitterMap/react-native/pull/185/commits/4aa804df21885ecef8fe7f103efdb76105b34239) and [f796bac](https://github.com/OpenLitterMap/react-native/pull/185/commits/f796bac4ffba0151faa695b13ddce2c5bbdc7d2f) which can bring back the issues we had with master.

**Comment by xlcrr** [comment]
@sudoDeznit app builds for me on main and staging... I think we can merge

**Review by sudoDeznit — APPROVED** [review]

**Comment by xlcrr** [comment]
@sudoDeznit can you fix this merge conflict please

**Pull request merged**
